### ISSUE TITLE
Pretraining 

### ISSUE THREAD

**Issue by SunQilin** [kagrze/disgram#1]
Thank you for sharing this code. I have some questiones about the code?
In prepare_train_and_test.sh, why pre-training is needed? Pre-training is not described in the paper.

**Comment by kagrze** [comment]
The pre-training phase is mentioned at the end of [appendix A](http://anthology.aclweb.org/attachments/D/D18/D18-1174.Attachment.zip):
> Finally, to speed up the fitting of embeddings for rare words, we initially tie sense disambiguation vectors q_ds between all words d ∈ D. In order to obtain a balanced initial distribution of senses we use a small negative entropy cost (γ = −0.1) in this phase. After the initialization, we untie sense disambiguation vectors and let each word fit its own disambiguation model.

It is described in greater detail in section 4.1.1 of [my thesis](https://arxiv.org/abs/1901.01695).
